//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity.beautyparlor;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ExpenseDetailActivity_
    extends ExpenseDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_beautyparlor_expense_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ExpenseDetailActivity_.IntentBuilder_ intent(Context context) {
        return new ExpenseDetailActivity_.IntentBuilder_(context);
    }

    public static ExpenseDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ExpenseDetailActivity_.IntentBuilder_(fragment);
    }

    public static ExpenseDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ExpenseDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_start_date = ((TextView) hasViews.findViewById(id.tv_start_date));
        tv_end_date = ((TextView) hasViews.findViewById(id.tv_end_date));
        tv_proposal_expense = ((TextView) hasViews.findViewById(id.tv_proposal_expense));
        tv_guanggao_expense = ((TextView) hasViews.findViewById(id.tv_guanggao_expense));
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ExpenseDetailActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        if (tv_start_date!= null) {
            tv_start_date.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ExpenseDetailActivity_.this.tv_start_date();
                }

            }
            );
        }
        if (tv_end_date!= null) {
            tv_end_date.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ExpenseDetailActivity_.this.tv_end_date();
                }

            }
            );
        }
        initView();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ExpenseDetailActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ExpenseDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ExpenseDetailActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ExpenseDetailActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
