//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity.beautyparlor;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyGuangGaoDetailActivity_
    extends MyGuangGaoDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String T_TYPE_EXTRA = "tType";
    public final static String G_ID_EXTRA = "gId";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_beautyparlor_my_guanggao_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MyGuangGaoDetailActivity_.IntentBuilder_ intent(Context context) {
        return new MyGuangGaoDetailActivity_.IntentBuilder_(context);
    }

    public static MyGuangGaoDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new MyGuangGaoDetailActivity_.IntentBuilder_(fragment);
    }

    public static MyGuangGaoDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new MyGuangGaoDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_publish_time = ((TextView) hasViews.findViewById(id.tv_publish_time));
        tv_pinglun_count = ((TextView) hasViews.findViewById(id.tv_pinglun_count));
        iv_pic = ((ImageView) hasViews.findViewById(id.iv_pic));
        tv_title = ((TextView) hasViews.findViewById(id.tv_title));
        ll_pics = ((LinearLayout) hasViews.findViewById(id.ll_pics));
        iv_pic1 = ((ImageView) hasViews.findViewById(id.iv_pic1));
        iv_pic2 = ((ImageView) hasViews.findViewById(id.iv_pic2));
        gv_pics = ((GridView) hasViews.findViewById(id.gv_pics));
        tv_content = ((TextView) hasViews.findViewById(id.tv_content));
        tv_zan_count = ((TextView) hasViews.findViewById(id.tv_zan_count));
        iv_pinglun = ((ImageView) hasViews.findViewById(id.iv_pinglun));
        lv_pinglun = ((ListView) hasViews.findViewById(id.lv_pinglun));
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyGuangGaoDetailActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        getData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(T_TYPE_EXTRA)) {
                tType = extras_.getInt(T_TYPE_EXTRA);
            }
            if (extras_.containsKey(G_ID_EXTRA)) {
                gId = extras_.getInt(G_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<MyGuangGaoDetailActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, MyGuangGaoDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), MyGuangGaoDetailActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), MyGuangGaoDetailActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public MyGuangGaoDetailActivity_.IntentBuilder_ tType(int tType) {
            return super.extra(T_TYPE_EXTRA, tType);
        }

        public MyGuangGaoDetailActivity_.IntentBuilder_ gId(int gId) {
            return super.extra(G_ID_EXTRA, gId);
        }

    }

}
