//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity.consumer;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.GridView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ProposalRequestPublishActivity_
    extends ProposalRequestPublishActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String JUMPFROMSHOUYE_EXTRA = "jumpfromshouye";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_consumer_proposal_publish);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProposalRequestPublishActivity_.IntentBuilder_ intent(Context context) {
        return new ProposalRequestPublishActivity_.IntentBuilder_(context);
    }

    public static ProposalRequestPublishActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProposalRequestPublishActivity_.IntentBuilder_(fragment);
    }

    public static ProposalRequestPublishActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProposalRequestPublishActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tv_address = ((TextView) hasViews.findViewById(id.tv_address));
        rl_projectType = ((RelativeLayout) hasViews.findViewById(id.rl_projectType));
        gv_patient_pics = ((GridView) hasViews.findViewById(id.gv_patient_pics));
        et_content = ((EditText) hasViews.findViewById(id.et_content));
        tv_projectType = ((TextView) hasViews.findViewById(id.tv_projectType));
        {
            View view = hasViews.findViewById(id.btn_publish);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProposalRequestPublishActivity_.this.btn_publish();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProposalRequestPublishActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        if (rl_projectType!= null) {
            rl_projectType.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ProposalRequestPublishActivity_.this.rl_projectType();
                }

            }
            );
        }
        initViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(JUMPFROMSHOUYE_EXTRA)) {
                jumpfromshouye = extras_.getString(JUMPFROMSHOUYE_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ProposalRequestPublishActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ProposalRequestPublishActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ProposalRequestPublishActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ProposalRequestPublishActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public ProposalRequestPublishActivity_.IntentBuilder_ jumpfromshouye(String jumpfromshouye) {
            return super.extra(JUMPFROMSHOUYE_EXTRA, jumpfromshouye);
        }

    }

}
