//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity.consumer;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import com.handmark.pulltorefresh.library.PullToRefreshListView;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class SearchFriendsActivity_
    extends SearchFriendsActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_consumer_search_friends);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static SearchFriendsActivity_.IntentBuilder_ intent(Context context) {
        return new SearchFriendsActivity_.IntentBuilder_(context);
    }

    public static SearchFriendsActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new SearchFriendsActivity_.IntentBuilder_(fragment);
    }

    public static SearchFriendsActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new SearchFriendsActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        et_search = ((EditText) hasViews.findViewById(id.et_search));
        btn_search = ((Button) hasViews.findViewById(id.btn_search));
        lv_search_friends_list = ((PullToRefreshListView) hasViews.findViewById(id.lv_search_friends_list));
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SearchFriendsActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        if (et_search!= null) {
            et_search.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SearchFriendsActivity_.this.et_search();
                }

            }
            );
        }
        if (btn_search!= null) {
            btn_search.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    SearchFriendsActivity_.this.btn_search();
                }

            }
            );
        }
        setView();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<SearchFriendsActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, SearchFriendsActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), SearchFriendsActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), SearchFriendsActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
