//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity.consumer;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import com.doublefi123.diary.widget.CircularImage;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class UpdatePeronalInfoActivity_
    extends UpdatePeronalInfoActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String SALEMAN_EXTRA = "saleman";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_consumer_update_personal_info);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static UpdatePeronalInfoActivity_.IntentBuilder_ intent(Context context) {
        return new UpdatePeronalInfoActivity_.IntentBuilder_(context);
    }

    public static UpdatePeronalInfoActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new UpdatePeronalInfoActivity_.IntentBuilder_(fragment);
    }

    public static UpdatePeronalInfoActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new UpdatePeronalInfoActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        et_user_nick = ((EditText) hasViews.findViewById(id.et_user_nick));
        radioFemale = ((RadioButton) hasViews.findViewById(id.radioFemale));
        rg_sex = ((RadioGroup) hasViews.findViewById(id.rg_sex));
        et_age = ((EditText) hasViews.findViewById(id.et_age));
        et_account_bank = ((EditText) hasViews.findViewById(id.et_account_bank));
        et_account_number = ((EditText) hasViews.findViewById(id.et_account_number));
        et_address = ((EditText) hasViews.findViewById(id.et_address));
        ll_account_info = ((LinearLayout) hasViews.findViewById(id.ll_account_info));
        iv_my_photo = ((CircularImage) hasViews.findViewById(id.iv_my_photo));
        et_sign = ((EditText) hasViews.findViewById(id.et_sign));
        radioMan = ((RadioButton) hasViews.findViewById(id.radioMan));
        {
            View view = hasViews.findViewById(id.btn_submit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        UpdatePeronalInfoActivity_.this.btn_submit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        UpdatePeronalInfoActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        if (iv_my_photo!= null) {
            iv_my_photo.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    UpdatePeronalInfoActivity_.this.iv_my_photo();
                }

            }
            );
        }
        initView();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(SALEMAN_EXTRA)) {
                saleman = extras_.getInt(SALEMAN_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<UpdatePeronalInfoActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, UpdatePeronalInfoActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), UpdatePeronalInfoActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), UpdatePeronalInfoActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public UpdatePeronalInfoActivity_.IntentBuilder_ saleman(int saleman) {
            return super.extra(SALEMAN_EXTRA, saleman);
        }

    }

}
