//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.entity;

import android.content.Context;

public final class MeiYouQuanListObject_
    extends MeiYouQuanListObject
{

    private Context context_;

    private MeiYouQuanListObject_(Context context) {
        context_ = context;
        init_();
    }

    public static MeiYouQuanListObject_ getInstance_(Context context) {
        return new MeiYouQuanListObject_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
