//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.entity;

import android.content.Context;

public final class MeiYouQuanListObject1_
    extends MeiYouQuanListObject1
{

    private Context context_;

    private MeiYouQuanListObject1_(Context context) {
        context_ = context;
        init_();
    }

    public static MeiYouQuanListObject1_ getInstance_(Context context) {
        return new MeiYouQuanListObject1_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
