//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import com.henglianmobile.beautyparlor.R.id;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BeautyParlorQualificationActivity_
    extends BeautyParlorQualificationActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String USER_ID_EXTRA = "userId";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_beautyparlor_qualification);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BeautyParlorQualificationActivity_.IntentBuilder_ intent(Context context) {
        return new BeautyParlorQualificationActivity_.IntentBuilder_(context);
    }

    public static BeautyParlorQualificationActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new BeautyParlorQualificationActivity_.IntentBuilder_(fragment);
    }

    public static BeautyParlorQualificationActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new BeautyParlorQualificationActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        iv_certificate = ((ImageView) hasViews.findViewById(id.iv_certificate));
        et_phone = ((EditText) hasViews.findViewById(id.et_phone));
        iv_jishi_photo = ((ImageView) hasViews.findViewById(id.iv_jishi_photo));
        iv_company_pic = ((ImageView) hasViews.findViewById(id.iv_company_pic));
        et_beautyparlor_name = ((EditText) hasViews.findViewById(id.et_beautyparlor_name));
        et_address = ((EditText) hasViews.findViewById(id.et_address));
        et_manager = ((EditText) hasViews.findViewById(id.et_manager));
        et_employee_count = ((EditText) hasViews.findViewById(id.et_employee_count));
        et_technician = ((EditText) hasViews.findViewById(id.et_technician));
        iv_zizhizhengshu = ((ImageView) hasViews.findViewById(id.iv_zizhizhengshu));
        et_beautyparlor_introduce = ((EditText) hasViews.findViewById(id.et_beautyparlor_introduce));
        if (iv_company_pic!= null) {
            iv_company_pic.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    BeautyParlorQualificationActivity_.this.iv_company_pic();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.tv_submit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BeautyParlorQualificationActivity_.this.tv_submit();
                    }

                }
                );
            }
        }
        if (iv_certificate!= null) {
            iv_certificate.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    BeautyParlorQualificationActivity_.this.iv_certificate();
                }

            }
            );
        }
        if (iv_jishi_photo!= null) {
            iv_jishi_photo.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    BeautyParlorQualificationActivity_.this.iv_jishi_photo();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        BeautyParlorQualificationActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        if (iv_zizhizhengshu!= null) {
            iv_zizhizhengshu.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    BeautyParlorQualificationActivity_.this.iv_zizhizhengshu();
                }

            }
            );
        }
        initAttrs();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(USER_ID_EXTRA)) {
                userId = extras_.getString(USER_ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<BeautyParlorQualificationActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, BeautyParlorQualificationActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), BeautyParlorQualificationActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), BeautyParlorQualificationActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public BeautyParlorQualificationActivity_.IntentBuilder_ userId(String userId) {
            return super.extra(USER_ID_EXTRA, userId);
        }

    }

}
