//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.handmark.pulltorefresh.library.PullToRefreshListView;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MeBeautyParlorFragment_
    extends com.henglianmobile.beautyparlor.ui.fragment.MeBeautyParlorFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_me_beauty_parlor, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MeBeautyParlorFragment_.FragmentBuilder_ builder() {
        return new MeBeautyParlorFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ll_my_account = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_my_account));
        iv_beautyparlor_photo = ((ImageView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.iv_beautyparlor_photo));
        tv_my_information = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_my_information));
        tv_publish_guanggao = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_publish_guanggao));
        tv_beautyparlor_address = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_beautyparlor_address));
        tv_account_money = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_account_money));
        ll_publish = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_publish));
        tv_beautyparlor_phone = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_beautyparlor_phone));
        tv_my_proposal = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_my_proposal));
        tv_my_account = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_my_account));
        lv_beautyparlor_me_list = ((PullToRefreshListView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.lv_beautyparlor_me_list));
        tv_beautyparlor_name = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_beautyparlor_name));
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_expense_details);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeBeautyParlorFragment_.this.ll_expense_details();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_publish);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeBeautyParlorFragment_.this.tv_publish();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.btn_logout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeBeautyParlorFragment_.this.btn_logout();
                    }

                }
                );
            }
        }
        if (tv_my_proposal!= null) {
            tv_my_proposal.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    MeBeautyParlorFragment_.this.tv_my_proposal();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_recharge);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeBeautyParlorFragment_.this.ll_recharge();
                    }

                }
                );
            }
        }
        if (tv_publish_guanggao!= null) {
            tv_publish_guanggao.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    MeBeautyParlorFragment_.this.tv_publish_guanggao();
                }

            }
            );
        }
        if (tv_my_account!= null) {
            tv_my_account.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    MeBeautyParlorFragment_.this.tv_my_account();
                }

            }
            );
        }
        if (tv_my_information!= null) {
            tv_my_information.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    MeBeautyParlorFragment_.this.tv_my_information();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.iv_beautyparlor_info_edit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeBeautyParlorFragment_.this.iv_beautyparlor_info_edit();
                    }

                }
                );
            }
        }
        setView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<MeBeautyParlorFragment_.FragmentBuilder_, com.henglianmobile.beautyparlor.ui.fragment.MeBeautyParlorFragment>
    {


        @Override
        public com.henglianmobile.beautyparlor.ui.fragment.MeBeautyParlorFragment build() {
            MeBeautyParlorFragment_ fragment_ = new MeBeautyParlorFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
