//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import com.handmark.pulltorefresh.library.PullToRefreshListView;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MeiYouQuanFragment_
    extends com.henglianmobile.beautyparlor.ui.fragment.MeiYouQuanFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_meiyouquan, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MeiYouQuanFragment_.FragmentBuilder_ builder() {
        return new MeiYouQuanFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        lv_meiyouquan_list = ((PullToRefreshListView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.lv_meiyouquan_list));
        btn_back = ((Button) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.btn_back));
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.iv_publish);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MeiYouQuanFragment_.this.iv_publish();
                    }

                }
                );
            }
        }
        if (btn_back!= null) {
            btn_back.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    MeiYouQuanFragment_.this.btn_back();
                }

            }
            );
        }
        setView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<MeiYouQuanFragment_.FragmentBuilder_, com.henglianmobile.beautyparlor.ui.fragment.MeiYouQuanFragment>
    {


        @Override
        public com.henglianmobile.beautyparlor.ui.fragment.MeiYouQuanFragment build() {
            MeiYouQuanFragment_ fragment_ = new MeiYouQuanFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
