//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ShouYeFragment_
    extends com.henglianmobile.beautyparlor.ui.fragment.ShouYeFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_shouye, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ShouYeFragment_.FragmentBuilder_ builder() {
        return new ShouYeFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        iv_left = ((ImageView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.iv_left));
        ll_left = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_left));
        if (ll_left!= null) {
            ll_left.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    ShouYeFragment_.this.ll_left();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ShouYeFragment_.this.ll_right();
                    }

                }
                );
            }
        }
        setView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ShouYeFragment_.FragmentBuilder_, com.henglianmobile.beautyparlor.ui.fragment.ShouYeFragment>
    {


        @Override
        public com.henglianmobile.beautyparlor.ui.fragment.ShouYeFragment build() {
            ShouYeFragment_ fragment_ = new ShouYeFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
