//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.henglianmobile.beautyparlor.ui.activity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.webkit.WebView;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import com.henglianmobile.beautyparlor.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ZiXunDetailActivity_
    extends ZiXunDetailActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String T_TYPE_EXTRA = "tType";
    public final static String ID_EXTRA = "id";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_zixun_detail);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
        requestWindowFeature(1);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ZiXunDetailActivity_.IntentBuilder_ intent(Context context) {
        return new ZiXunDetailActivity_.IntentBuilder_(context);
    }

    public static ZiXunDetailActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ZiXunDetailActivity_.IntentBuilder_(fragment);
    }

    public static ZiXunDetailActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ZiXunDetailActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ll_meiyou_pics = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_meiyou_pics));
        lv_pinglun = ((ListView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.lv_pinglun));
        ll_bottom = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_bottom));
        tv_zan_count = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_zan_count));
        ll_submit_commit = ((LinearLayout) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.ll_submit_commit));
        wv_zixun = ((WebView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.wv_zixun));
        et_comment = ((EditText) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.et_comment));
        tv_pinglun_count = ((TextView) hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.tv_pinglun_count));
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.iv_comment_bottom);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ZiXunDetailActivity_.this.iv_comment_bottom();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.btn_send);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ZiXunDetailActivity_.this.btn_send();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.henglianmobile.beautyparlor.R.id.btn_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ZiXunDetailActivity_.this.btn_back();
                    }

                }
                );
            }
        }
        setData();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(T_TYPE_EXTRA)) {
                tType = extras_.getInt(T_TYPE_EXTRA);
            }
            if (extras_.containsKey(ID_EXTRA)) {
                id = extras_.getInt(ID_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ZiXunDetailActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ZiXunDetailActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ZiXunDetailActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ZiXunDetailActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public ZiXunDetailActivity_.IntentBuilder_ tType(int tType) {
            return super.extra(T_TYPE_EXTRA, tType);
        }

        public ZiXunDetailActivity_.IntentBuilder_ id(int id) {
            return super.extra(ID_EXTRA, id);
        }

    }

}
